server:
  port: 7201
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/imagine1717/microconfig.git
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672    # RabbitMQ的监听端口
    username: guest  # 用户名
    password: guest # 密码
  application:
    name: microcloud-config-bus

eureka:
 client:
  serviceUrl:
    defaultZone: http://admin:123@localhost:7004/eureka
 instance:
    prefer-ip-address: true # 在地址栏上使用IP地址进行显示
    instance-id: microcloud-config-bus
management:
  endpoints:
    web:
      exposure:
        include: "*"