spring:
   profiles:
      active:
        - dev
---
server:
  port: 8201

spring:
  profiles: dev
  application:
      name: microconfig-test-client33

eureka:
 client:
  service-url:
    defaultZone: http://admin:123@localhost:7004/eureka

info:
  app.name: microcloud-config-client-dev22
  company.name: enjoy2222

---
server:
  port: 8102

spring:
  profiles: beta
  application:
      name: microconfig-test-client2

eureka:
 client:
  service-url:
    defaultZone: http://admin:123@localhost:7001/eureka

