server:
  port: 8080

mybatis:
  mapper-locations:
    - classpath:mapping/*.xml
spring:
  profiles:
    active: beta
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.jdbc.Driver # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=GMT%2B8 # 数据库连接地址
    username: root # 数据库用户名
    password: root # 数据库连接密码
  application:
    name: microcloud-config-product-client
#  security:
#    user:
#      name: admin #认证用户
#      password: 123 #认证密码
#      roles:
#        - USER # 授权角色

logging:
  level:
      cn.enjoy.mapper: debug
eureka:
  client:
    service-url:
#      defaultZone: http://admin:123@localhost:7001/eureka
      defaultZone: http://admin:123@eureka1:7001/eureka,http://admin:123@eureka2:7002/eureka,http://admin:123@eureka3:7003/eureka
  instance:
    instance-id: microcloud-config-product-client
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-renewal-interval-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）

info:
  app.name: microcloud-config-product-client
  company.name: enjoy
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$


