spring:
  profiles:
    active:
      - dev
---
server:
  port: 7001
eureka:
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:123@localhost:7001/eureka
  instance: # eureak实例定义
    hostname: localhost # 定义 Eureka 实例所在的主机名称
spring:
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: 123
  application:
    name: microcloud-config-eureka-client
---
server:
  port: 7002

spring:
  profiles:
    active: beta
  security:
    user:
      name: admin
      password: 123
  application:
    name: microcloud-config-eureka-client

eureka:
  server:
    eviction-interval-timer-in-ms: 1000 #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:123@eureka1:7001/eureka
  instance: # 实例定义
    hostname: eureka1 # 定义 eureka 实例所在的主机
